curl --url ^"https://moon.peakstorm.top/vd/T3JCeFQzTXpLRjlFb3hlc0lza3h0UTotQ01LTmxqemFZMVhvZ0dZaFNhSk9KTEQ3TW9tYWhKbUpCTVRYMG5kVXZF/index-s1080p-v1-a1.m3u8^" ^
  -H ^"accept: */*^" ^
  -H ^"accept-language: en-US,en;q=0.8^" ^
  -H ^"cache-control: no-cache^" ^
  -H ^"origin: https://www.vidy.st^" ^
  -H ^"pragma: no-cache^" ^
  -H ^"priority: u=1, i^" ^
  -H ^"referer: https://www.vidy.st/^" ^
  -H ^"sec-ch-ua: ^\^"Brave^\^";v=^\^"153^\^", ^\^"Not_A Brand^\^";v=^\^"8^\^", ^\^"Chromium^\^";v=^\^"153^\^"^" ^
  -H ^"sec-ch-ua-mobile: ?0^" ^
  -H ^"sec-ch-ua-platform: ^\^"Windows^\^"^" ^
  -H ^"sec-fetch-dest: empty^" ^
  -H ^"sec-fetch-mode: cors^" ^
  -H ^"sec-fetch-site: cross-site^" ^
  -H ^"sec-gpc: 1^" ^
  -H ^"user-agent: Mozilla/5.0 ^(Windows NT 10.0; Win64; x64^) AppleWebKit/537.36 ^(KHTML, like Gecko^) Chrome/153.0.0.0 Safari/537.36^"